---
Parameters:
  AccountBName:
    Description: "Account B's name (used for naming resources)"
    Type: String
  AccountBID:
    Description: "Account B's account ID"
    Type: String
   
Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "BucketOwnerFullControl"
      
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS:
                - !Join [":", ["arn:aws:iam:", Ref: "AccountBID", "root"]]
            Action:
              - "s3:PutObject"
            Resource: !Join ["", ["arn:aws:s3:::", Ref: "Bucket", "/*"]]
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          -
            Effect: "Allow"
            Principal:
              AWS:
                - !Join [":", ["arn:aws:iam:", Ref: "AccountBID", "root"]]
            Action:
              - "s3:ListBucket"
            Resource: !Join ["", ["arn:aws:s3:::", Ref: "Bucket"]]
                
Outputs:
  Bucket:
    Value: !Ref Bucket
    Description: "Bucket for Account B"